server:
  port: 8011

spring:
  application:
    name: service3

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true # 유레카 서비스에 (자신을) 등록 여부
    fetch-registry: true
    serviceUrl:
      defaultZone: http://54.238.193.86:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"
