apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
  namespace: springboot1
  labels:
    app: springboot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot
  template:
    metadata:
      labels:
        app: springboot
    spec:
      containers:
      - name: springboot
        image: harbor.aikoo.net/tanzu/springboot:1.1
        ports:
        - containerPort: 8012

