apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: springboot
  name: springboot
  namespace: springboot
spec:
  ports:
  - port: 8012
    protocol: TCP
    targetPort: 8012
  selector:
    app: springboot
  type: ClusterIP
status:
  loadBalancer: {}
